use_frameworks!

platform :ios, '10.0'

target 'DetalhesMoedas_Example' do
  pod 'DetalhesMoedas', :path => '../'
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.7.0'
  pod 'AlamofireImage', '~> 3.4.0'
  pod 'ModCommons', :git => 'https://github.com/leojportes/CriptoBeca', :branch => 'develop' 
  

  target 'DetalhesMoedas_Tests' do
    inherit! :search_paths

    
  end
end
