use_frameworks!

platform :ios, '10.0'

target 'DetalhesMoedas_Example' do
  pod 'DetalhesMoedas', :path => '../'
  pod 'SwiftLint'
  pod 'Commons', :git=> 'https://github.com/leojportes/Commons.git', :branch=> 'develop'
  

  target 'DetalhesMoedas_Tests' do
    inherit! :search_paths

    
  end
end
